inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environment.rb'
    - 'config/boot.rb'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'config.ru'
    - 'Rakefile'

Layout/AlignHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Lint/UriEscapeUnescape:
  Enabled: false
